name: CI

on:
  push:
  pull_request:

env:
  EXPECTED_N: "100"   # set to the N you used (e.g., 10 or 100)

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python - << 'PY'
import sys, subprocess
try:
    import yaml  # noqa
except Exception:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pyyaml"])
PY

      - name: CI report from results/summary.json
        run: |
          python scripts/ci_check.py \
            --summary results/summary.json \
            --expected-n "${EXPECTED_N}" || true

      - name: Upload artifacts (normalized outputs)
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            results/summary.json
            runs_normalized/*.yaml
          if-no-files-found: warn
